-- ============================================================
-- 007 — HYBRID SCHEDULING SYSTEM (Slot + Window)
-- Run in Supabase SQL Editor AFTER 006_scheduling_system.sql
-- ============================================================
-- Adds:
--   • services.requires_slot       — toggles slot vs window mode
--   • services.slot_duration_min   — duration of each slot
--   • services.max_slots_per_day   — hard cap on daily bookings
--   • service_slot_config          — per-service slot shape (capacity, buffer)
--   • service_slots                — actual bookable slots per date
--   • jobs.slot_id                 — FK to the booked slot (slot mode)
-- ============================================================

-- ── 1. Extend services table ──────────────────────────────

ALTER TABLE public.services
  ADD COLUMN IF NOT EXISTS requires_slot      BOOLEAN     NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS slot_duration_min  INTEGER,           -- e.g. 60, 90, 120
  ADD COLUMN IF NOT EXISTS max_slots_per_day  INTEGER,           -- e.g. 8 (null = unlimited by config)
  ADD COLUMN IF NOT EXISTS base_price         DECIMAL(10,2);     -- alias, keep price col too

-- Back-fill base_price from price (they're the same column concept)
UPDATE public.services SET base_price = price WHERE base_price IS NULL;

-- ── 2. service_slot_config ────────────────────────────────
-- Per-service configuration: how many slots to generate, buffer between slots, etc.

CREATE TABLE IF NOT EXISTS public.service_slot_config (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id       UUID NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  worker_id        UUID NOT NULL REFERENCES public.worker_profiles(id) ON DELETE CASCADE,

  -- Slot shape
  slot_duration_min  INTEGER  NOT NULL DEFAULT 60,     -- minutes per slot
  buffer_min         INTEGER  NOT NULL DEFAULT 15,     -- gap between slots
  capacity           INTEGER  NOT NULL DEFAULT 1,      -- simultaneous bookings per slot

  -- Daily limits
  max_slots_per_day  INTEGER  NOT NULL DEFAULT 8,

  -- Auto-generate slots from worker_availability
  auto_generate      BOOLEAN  NOT NULL DEFAULT true,

  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_slot_config_service UNIQUE (service_id)
);

CREATE INDEX IF NOT EXISTS idx_slot_config_worker ON public.service_slot_config(worker_id);

-- ── 3. service_slots ──────────────────────────────────────
-- Actual bookable time slots. Generated by worker or auto from config.

CREATE TABLE IF NOT EXISTS public.service_slots (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id     UUID NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  worker_id      UUID NOT NULL REFERENCES public.worker_profiles(id) ON DELETE CASCADE,

  slot_date      DATE         NOT NULL,
  slot_start     TIME         NOT NULL,
  slot_end       TIME         NOT NULL,

  -- Capacity tracking
  capacity       INTEGER      NOT NULL DEFAULT 1,
  booked_count   INTEGER      NOT NULL DEFAULT 0,

  -- Status
  is_blocked     BOOLEAN      NOT NULL DEFAULT false,   -- manually blocked by worker
  block_reason   VARCHAR(100),

  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_slot UNIQUE (worker_id, service_id, slot_date, slot_start),
  CONSTRAINT chk_slot_times CHECK (slot_end > slot_start),
  CONSTRAINT chk_booked_count CHECK (booked_count >= 0 AND booked_count <= capacity)
);

CREATE INDEX IF NOT EXISTS idx_slots_worker_date
  ON public.service_slots(worker_id, slot_date)
  WHERE is_blocked = false;

CREATE INDEX IF NOT EXISTS idx_slots_service_date
  ON public.service_slots(service_id, slot_date)
  WHERE is_blocked = false AND booked_count < capacity;

-- ── 4. Extend jobs table ──────────────────────────────────

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS slot_id  UUID REFERENCES public.service_slots(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_jobs_slot ON public.jobs(slot_id) WHERE slot_id IS NOT NULL;

-- ── 5. Helper function — is slot still available? ─────────

CREATE OR REPLACE FUNCTION public.slot_available(p_slot_id UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE AS $$
  SELECT
    COALESCE(
      (SELECT booked_count < capacity AND NOT is_blocked
       FROM public.service_slots
       WHERE id = p_slot_id),
      false
    );
$$;

-- ── 6. Trigger — keep booked_count in sync ────────────────
-- When a job with a slot_id is created/cancelled, adjust booked_count.

CREATE OR REPLACE FUNCTION public.update_slot_booking_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  -- Job just got a slot assigned (INSERT or UPDATE setting slot_id)
  IF (TG_OP = 'INSERT' AND NEW.slot_id IS NOT NULL) OR
     (TG_OP = 'UPDATE' AND NEW.slot_id IS NOT NULL AND
      (OLD.slot_id IS DISTINCT FROM NEW.slot_id OR OLD.status = 'cancelled')) THEN
    UPDATE public.service_slots
    SET booked_count = booked_count + 1
    WHERE id = NEW.slot_id;
  END IF;

  -- Job cancelled or slot removed
  IF TG_OP = 'UPDATE' AND OLD.slot_id IS NOT NULL AND
     (NEW.status IN ('cancelled', 'failed') OR NEW.slot_id IS NULL) AND
     OLD.status NOT IN ('cancelled', 'failed') THEN
    UPDATE public.service_slots
    SET booked_count = GREATEST(0, booked_count - 1)
    WHERE id = OLD.slot_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_slot_booking ON public.jobs;
CREATE TRIGGER trg_slot_booking
  AFTER INSERT OR UPDATE ON public.jobs
  FOR EACH ROW EXECUTE FUNCTION public.update_slot_booking_count();

-- ── 7. Seed: mark existing services as window-based ───────
-- All services created before 007 use the flexible window system.
UPDATE public.services SET requires_slot = false WHERE requires_slot IS NULL;

-- ── 8. Grant permissions (RLS-friendly) ──────────────────
-- service_slot_config and service_slots inherit the same RLS pattern as services.
ALTER TABLE public.service_slot_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_slots       ENABLE ROW LEVEL SECURITY;

-- Anyone can read slots (for discovery calendar)
DROP POLICY IF EXISTS "slots_public_read"          ON public.service_slots;
DROP POLICY IF EXISTS "slot_config_public_read"    ON public.service_slot_config;
DROP POLICY IF EXISTS "slots_worker_manage"        ON public.service_slots;
DROP POLICY IF EXISTS "slot_config_worker_manage"  ON public.service_slot_config;

CREATE POLICY "slots_public_read"
  ON public.service_slots FOR SELECT USING (true);

CREATE POLICY "slot_config_public_read"
  ON public.service_slot_config FOR SELECT USING (true);

-- Workers can manage their own slots
CREATE POLICY "slots_worker_manage"
  ON public.service_slots FOR ALL
  USING (
    worker_id IN (
      SELECT id FROM public.worker_profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "slot_config_worker_manage"
  ON public.service_slot_config FOR ALL
  USING (
    worker_id IN (
      SELECT id FROM public.worker_profiles WHERE user_id = auth.uid()
    )
  );
